apps/preprocess.py
added the main preprocessing functions with the following structure as output: 
return a list of lists, containing [word_start_index, word_end_index, word]
=> added the intial preprocessing functions

src/static/script.js, src/static/style.css
popup to hover
resize popup margin
popup color change to match buttons
=> small fixes

apps/preprocess.py
Added the main class, called Dictionary, responsible for doing whatever has something to do with the input dictionary. I'm also going to add some comments soon. I just wanted to make sure that we can make some progress by tomorrow, and I will add the comments hopefully in two days.
=> added the dictionary class to do the dictionary related tasks

src/apps/spellchecker.py, src/main.py, src/templates/index.html
The functional spell_checker is added. It has all the functionality we needed for now, except capitalization. This feature can be added to the feature. 
I also faced some weak points while coding it which I'm going to discuss more at our face-to-face meeting.
=> Dev spell checker

src/apps/spellchecker.py, src/main.py, src/static/async.js, src/static/script.js, src/templates/index.html
In this PR, the following commits and changes have been applied to the program:
* The initial functions and adjustments to make the programmer asynchronous are taken. You can find the primary function in ``` \static\async.js```
* Some unnecessary imported libraries are now deleted - since it could make version conflict and download extra files on the client side. 
* Some changes are made to the ```main.py``` to handle errors while communicating with the client-side. 
* Two previous JS functions are deleted as we no longer use them in the new version of the application.
=> Spell async

src/templates/index.html
I added a function to count the words.
=> Updated index.html

src/apps/langSpec.py, src/apps/spellchecker.py, src/main.py, src/static/css/style.css, src/static/js/async.js, src/static/js/script.js, src/templates/index.html
Hi guys, in this PR, I updated the UI. As we discussed in the last sprint planning, I updated the UI so that now the text gets updated inside the text box instead of somewhere else. In my opinion, it's not perfect, but it does the job well, and it looks nice. Please play around with it and report if you face any bugs. I already worked on some bugs I spotted and resolved them.
I'm also working on multilingual spell checking. You can check the code progress in the new class added to the ```LangSpec.py``` file.
=> Updated the overall UI and also added updated the LangSpec class 

src/static/css/style.css, src/static/js/async.js, src/static/js/script.js
Changed the styling of suggested candidates. As a feature, one can add some CSS animation to the way the suggestions show up or fade in. Since this is unnecessary, we can do it in the future.
=> modified the user interface styling for showing the candidates

src/static/js/async.js
The previous code didn't keep the empty spaces that the client intendedly wanted to keep. This is now solved.
=> Added a char replacement to keep spaces

README.md, requirements.txt, sluspell/apps/spellchecker.py, sluspell/main.py
Small changes on pathing and other files, such as README.
=> Structure change

sluspell/apps/langSpec.py, tests/open_test.py, tests/test.py
Added new classes called ```SpellCheckAPI``` and ```TestTextList```, to handle the new test set. 
The ```TestTextList``` class,  utilizes objects of ```SpellCheckAPI``` to get the possible output by SLUSpell app. Then it compares the outputs and displays an error if the output is wrong. Finally, it will return the runtime and accuracy for the test set.
=> Two new classes were added to the test files

README.md
just updating the readme.md file
=> Doc branch

sluspell/static/css/style.css, sluspell/static/js/script.js, sluspell/templates/index.html
Here I added the copy to clipboard button in html and also added its corresponding css and is.
=> Copy to clipboard function and button in html

sluspell/static/js/async.js
This bug showed up when we handled another bug and I just noticed. In this simple PR, it's solved.
=> fixed a bug regarding the misspelled highlighting.

.gitignore, sluspell/apps/langSpec.py, sluspell/apps/spellchecker.py
In this PR, the pattern for finding string chunks is modified and, in fact, more generalized to handle numbers and also some of the less used punctuations. 
There is also some replacement of characters just to handle bugs related to the user interface display.
=> Bug Fixed: Showing numbers and some punctuations in front end

sluspell/static/js/async.js
I changed the scope of async variables to local to prevent some bugs from happening.
=> changed the scope of variables to local

sluspell/static/js/async.js, sluspell/static/js/script.js
One of the things that made the client face some difficulties while using the app was interruptions while having an unstable internet connection. I added a handler to the async functions to handle the orders of clients' requests.
=> Added a request handler to the async function

sluspell/main.py, sluspell/static/js/async.js, sluspell/static/js/script.js, sluspell/templates/index.html
New changes are made to support more languages in the interface. Now Spanish and Farsi are also added to the menu.
=> Support more languages in the interface

sluspell/static/js/async.js
Just commented the console.log for the deployment.
=> commented out the console.log

sluspell/static/css/style.css, sluspell/static/js/script.js, sluspell/templates/index.html
Some simple accessibility tools are added.
=> added some simple accessibility and help tools for clients

sluspell/static/css/style.css, sluspell/templates/index.html
Made some corrections on the user interface and help sections.
=> improved the accessibility of the interface

sluspell/templates/index.html
I just changed the HTML file to handle multilingual help.
=> Added multilingual help
